<a href="https://colab.research.google.com/github/napoler/001pytorch/blob/master/bert_pre_mask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

     |████████████████████████████████| 1.9MB 5.8MB/s 
     |████████████████████████████████| 3.2MB 23.3MB/s 
     |████████████████████████████████| 890kB 35.0MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp37-none-any.whl size=893262 sha256=8068a0fce52772deb95109eb86a7a49377e25668ef1489af048b6c06bfdc0fbb
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [ ]:
 from transformers import BertTokenizer, BertForMaskedLM

In [ ]:
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')

inputs = tokenizer("The capital of France is [MASK].", return_tensors="pt")
labels = tokenizer("The capital of France is Paris.", return_tensors="pt")["input_ids"]

outputs = model(**inputs, labels=labels)
loss = outputs.loss
logits = outputs.logits

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
logits

tensor([[[ -6.4346,  -6.4063,  -6.4097,  ...,  -5.7691,  -5.6326,  -3.7883],
         [-14.0119, -14.7240, -14.2120,  ..., -11.6976, -10.7304, -12.7618],
         [ -9.6561, -10.3125,  -9.7459,  ...,  -8.7782,  -6.6036, -12.6596],
         ...,
         [ -3.7861,  -3.8572,  -3.5644,  ...,  -2.5593,  -3.1093,  -4.3820],
         [-11.6598, -11.4274, -11.9267,  ...,  -9.8772, -10.2103,  -4.7594],
         [-11.7266, -11.7509, -11.8040,  ..., -10.5943, -10.9407,  -7.5151]]],
       grad_fn=<AddBackward0>)

In [31]:
logits.size()

torch.Size([1, 9, 30522])

In [20]:
in=out["input_ids"].tolist()[0]

[101, 1996, 3007, 1997, 2605, 2003, 103, 1012, 102, 0]

In [23]:
len(in)

SyntaxError: ignored

In [30]:
for i in range(9):
  print(logits[0,i])
  print(logits[0,i].size())
  print(torch.argmax(logits[0,i]).item())
  print(tokenizer.convert_ids_to_tokens(torch.argmax(logits[0,i]).item()))

tensor([-6.4346, -6.4063, -6.4097,  ..., -5.7691, -5.6326, -3.7883],
       grad_fn=<SelectBackward>)
torch.Size([30522])
1012
.
tensor([-14.0119, -14.7240, -14.2120,  ..., -11.6976, -10.7304, -12.7618],
       grad_fn=<SelectBackward>)
torch.Size([30522])
1996
the
tensor([ -9.6561, -10.3125,  -9.7459,  ...,  -8.7782,  -6.6036, -12.6596],
       grad_fn=<SelectBackward>)
torch.Size([30522])
3007
capital
tensor([-14.4691, -15.1105, -14.8048,  ..., -12.1812, -11.0501, -14.8963],
       grad_fn=<SelectBackward>)
torch.Size([30522])
1997
of
tensor([-11.4073, -11.9343, -12.1147,  ...,  -8.6815,  -7.8381, -10.2984],
       grad_fn=<SelectBackward>)
torch.Size([30522])
2605
france
tensor([-10.8388, -11.3204, -10.6878,  ...,  -8.8217,  -4.8922, -13.8593],
       grad_fn=<SelectBackward>)
torch.Size([30522])
2003
is
tensor([-3.7861, -3.8572, -3.5644,  ..., -2.5593, -3.1093, -4.3820],
       grad_fn=<SelectBackward>)
torch.Size([30522])
3000
paris
tensor([-11.6598, -11.4274, -11.9267,  ...,  -9.

In [ ]:
out=model.prepare_inputs_for_generation(**inputs)
out

{'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 0]]),
 'input_ids': tensor([[ 101, 1996, 3007, 1997, 2605, 2003,  103, 1012,  102,    0]])}

In [ ]:
help(tokenizer)

In [ ]:
out["input_ids"].tolist()

[[101, 1996, 3007, 1997, 2605, 2003, 103, 1012, 102, 0]]

In [ ]:
inputs

{'input_ids': tensor([[ 101, 1996, 3007, 1997, 2605, 2003,  103, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
tokenizer.convert_ids_to_tokens(out["input_ids"].tolist()[0])

['[CLS]',
 'the',
 'capital',
 'of',
 'france',
 'is',
 '[MASK]',
 '.',
 '[SEP]',
 '[PAD]']